export const adminActionTypes = {
  LOADING_SPINNER: 'LOADING_SPINNER',
  IS_LOADING: 'IS_LOADING',

  FETCHING_ALL_USERS_PARCEL_ADMIN_START: 'FETCHING_ALL_USERS_PARCEL_ADMIN_START',
  FETCHING_ALL_USERS_PARCEL_ADMIN_SUCCESS: 'FETCHING_ALL_USERS_PARCEL_ADMIN_SUCCESS',
  FETCHING_ALL_USERS_PARCEL_ADMIN_FAILURE: 'FETCHING_ALL_USERS_PARCEL_ADMIN_FAILURE',

  FETCHING_ALL_USERS_DATA_START: 'FETCHING_ALL_USERS_DATA_START',
  FETCHING_ALL_USERS_DATA_SUCCESS: 'FETCHING_ALL_USERS_DATA_SUCCESS',
  FETCHING_ALL_USERS_DATA_FAILURE: 'FETCHING_ALL_USERS_DATA_FAILURE',

  SET_CURRENT_ADMIN_START: 'SET_CURRENT_ADMIN_START',
  SET_CURRENT_ADMIN_SUCCESS: 'SET_CURRENT_ADMIN_SUCCESS',
  SET_CURRENT_ADMIN_FAILURE: 'SET_CURRENT_ADMIN_FAILURE',

  TOGGLE_HOVER: 'TOGGLE_HOVER',
  TOGGLE_OPEN: 'TOGGLE_OPEN',
  SET_SELECTED_PARCEL: 'SET_SELECTED_PARCEL',
  SHOW_PARCEL: 'SHOW_PARCEL',
  EDIT_PARCEL: 'EDIT_PARCEL',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
};
