export const userActionTypes = {
  LOADING_SPINNER: 'LOADING_SPINNER',

  FETCHING_CURRENT_USER_START: 'FETCHING_CURRENT_USER_START',
  FETCHING_CURRENT_USER_SUCCESS: 'FETCHING_CURRENT_USER_SUCCESS',
  FETCHING_CURRENT_USER_FAILURE: 'FETCHING_CURRENT_USER_FAILURE',

  SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',

  SET_SCROLL_NAV: 'SET_SCROLL_NAV',
  TOGGLE_HOVER: 'TOGGLE_HOVER',
  TOGGLE_OPEN_MENU: 'TOGGLE_OPEN_MENU',
  TOGGLE_LOGOUT: 'TOGGLE_LOGOUT',
  LOGOUT: 'LOGOUT',
};
