export const parcelActionTypes = {
  IS_LOADING: 'IS_LOADING',
  CREATE_PARCEL: 'CREATE_PARCEL',

  FETCHING_USER_PARCEL_START: 'FETCHING_USER_PARCEL_START',
  FETCHING_USER_PARCEL_SUCCESS: 'FETCHING_USER_PARCEL_SUCCESS',
  FETCHING_USER_PARCEL_FAILURE: 'FETCHING_USER_PARCEL_FAILURE',

  SET_USER_PARCEL: 'SET_USER_PARCEL',
  SET_SELECTED_PARCEL: 'SET_SELECTED_PARCEL',
  SHOW_PARCEL:'SHOW_PARCEL',
  EDIT_PARCEL: 'EDIT_PARCEL'
};
